# All the messages send by the plugin.
messages:
  redirected:
    - "&f"
    - "&cAn kick occurred in your connection. &cReason:&r %reason%"
    - "&cYou have been send back to the main lobby."
    - "&f"

# The amount of time between checking if a server is online.
# Players won't be connected to offline servers.
check: 30

# Blacklist. When a kick message contains this word they will NOT get redirected.
#            This will result in the player seeing the kick screen.
blacklist:
  - "ban"

# Detect shutdown in server kick messages
#   This can be faster for when you want to shutdowns servers and using RedirectPlus to redirect those people.
detect-shutdown:
  enabled: true
  messages:
  - "shutdown"
  - "restart"
  - "closed"

# Don't show the redirect message if the message contains one of the following words.
# Can be useful when redirecting people from a game lobby and stuff.
no-messages:
  - "[Silent]"

# unknown-group / server
# This will redirect unknown servers to the group listed here:
unknown-group: lobby

# Server groups and their settings
groups:
  lobby:
    # If kicked from this server group, no redirects will happen.
    bottom-kick: true
    # Spread redirect people over the servers.
    spread: true
    # Parent group - If none of the servers are available, the parent group will be used.
    # Set to none if none. If the parent server group is needed the player will be kicked instead.
    parent-group: none
    servers:
      - lobby1
      - lobby2
    # Servers that are connected to this group, but they won't be redirected to:
    connected: {}
  games:
    bottom-kick: false
    spread: true
    parent-group: lobby
    # These servers do not have lobbies them self so we use a parent group.
    servers: {}
    connected:
      - survival
      - pvp

# EXAMPLE SETUP
#groups:
#  # The main lobby. If kicked from here they should not be redirected so we enable bottom-kick.
#  # There are no connected servers here.
#  main-lobby:
#    bottom-kick: true
#    spread: true
#    parent-group: none
#    servers:
#      - lobby1
#      - lobby2
#      - lobby3
#    connected: {}
#  # This is the survival games group.
#  # bottom-kick is false, since we want redirects from the connected servers.
#  # The lobby servers are in the 'servers' list (so they will be redirected to) and the game servers are in the 'connected' list.
#  survivalgames:
#    bottom-kick: false
#    spread: true
#    parent-group: none
#    servers:
#      - sg-lobby-1
#      - sg-lobby-2
#    conntected:
#      - sg-game-1
#      - sg-game-2
#      - sg-game-3
#      - sg-game-4
#      - sg-game-5